In [2]:
from numpy import asarray
from sklearn.preprocessing import MinMaxScaler

data = [[100, 0.001],
        [8, 0.05],
        [50, 0.005],
        [88, 0.07],
        [4, 0.1]]

print("Data Asli")
print(data)

scaler = MinMaxScaler()

print("Data transfrom hasil normalisasi")

scaled = scaler.fit_transform(data)
print(scaled)

Data Asli
[[100, 0.001], [8, 0.05], [50, 0.005], [88, 0.07], [4, 0.1]]
Data transfrom hasil normalisasi
[[1.         0.        ]
 [0.04166667 0.49494949]
 [0.47916667 0.04040404]
 [0.875      0.6969697 ]
 [0.         1.        ]]


In [1]:
#Manual Normalization

def norm_manual(data):
    n_max = max(data)
    n_min = min(data)
    l_data = len(data) #panjang data
    
    for i in range(0, l_data):
        data[i] = (data[i]- n_min) / (n_max - n_min)
   
    return data

In [2]:
nilai = [10, 23, 24, 12]
nilai_norm = norm_manual(nilai)
nilai_norm

[0.0, 0.9285714285714286, 1.0, 0.14285714285714285]

In [3]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler

data = [[100, 0.001],
        [8, 0.05],
        [50, 0.005],
        [88, 0.07],
        [4, 0.1]]

print("Data Asli")
print(data)

scaler = StandardScaler()

print("Data transfrom hasil normalisasi")

scaled = scaler.fit_transform(data)
print(scaled)

Data Asli
[[100, 0.001], [8, 0.05], [50, 0.005], [88, 0.07], [4, 0.1]]
Data transfrom hasil normalisasi
[[ 1.26398112 -1.16389967]
 [-1.06174414  0.12639634]
 [ 0.         -1.05856939]
 [ 0.96062565  0.65304778]
 [-1.16286263  1.44302493]]


In [4]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()

oe = [
    ['State Polytechnics of Malang'],
    ['Electronic State Polytechnics of Surabaya'],
    ['State Polytechnics of Jakarta '],
    ['State Polytechnics of Padang'],
    ['State Polytechnics of Bandung']
    ]

print(ordinal_encoder.fit_transform(oe))

[[3.]
 [0.]
 [2.]
 [4.]
 [1.]]


In [6]:
from sklearn.feature_extraction import DictVectorizer
onehot_encoder = DictVectorizer()

oe = [
    {'name' : 'State Polytechnics of Malang'},
    {'name' :'Electronic State Polytechnics of Surabaya'},
    {'name' :'State Polytechnics of Jakarta '},
    {'name' :'State Polytechnics of Padang'},
    {'name' :'State Polytechnics of Bandung'}
    ]

print(onehot_encoder.fit_transform(oe).toarray())

[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]


In [11]:
from sklearn.preprocessing import OneHotEncoder
dummy_encoding = OneHotEncoder(drop = 'first')

de = [
    ['State Polytechnics of Malang'],
    ['Electronic State Polytechnics of Surabaya'],
    ['State Polytechnics of Jakarta ']
    ]

print(dummy_encoding.fit_transform(de).toarray())

[[0. 1.]
 [0. 0.]
 [1. 0.]]


In [12]:
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

In [13]:
from urllib import response
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(corpus)
print(response)

  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811


In [16]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
corpus = ['the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story']

X = vectorizer.fit_transform(corpus)

features = vectorizer.get_feature_names()

features

['ate',
 'away',
 'cat',
 'end',
 'finally',
 'from',
 'had',
 'house',
 'little',
 'mouse',
 'of',
 'ran',
 'saw',
 'story',
 'the',
 'tiny']

In [1]:
with open("orange.txt") as f:
    for line in f:
        print(line)

:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:

         -----=====Earth's Dreamlands=====-----

           (313)558-5024 {14.4} (313)558-5517

              A BBS for text file junkies

              RPGNet GM File Archive Site

.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.



                The Five Orange Pips



  When I glance over my notes and records of the Sherlock

Holmes cases between the years '82 and '90, I am faced by so

many which present strange and interesting features that it is no

easy matter to know which to choose and which to leave. Some,

however, have already gained publicity through the papers, and

others have not offered a field for those peculiar qualities which

my friend possessed in so high a degree, and which it is the

object of these papers to illustrate. Some, too, have baffled his

analytical skill, and would be, as narratives, beginnings without

an ending, while others have been but partially cleared up, and

have t

In [3]:
z=open("orange.txt","r")
data = z.read().split()
data1 = z.read().splitlines()



from urllib import response
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words='english')
response = vectorizer.fit_transform(data)
features = vectorizer.get_feature_names()
print(data1)
print("")
print(features)
print("")
print("result")

print(response)

[]

['000', '10', '12th', '14', '1869', '1870', '1878', '1883', '1oth', '2d', '313', '4th', '5024', '5517', '558', '7th', '82', '83', '84', '85', '87', '90', '9th', 'abjure', 'able', 'abound', 'absence', 'absolute', 'abuse', 'accident', 'accidental', 'accidents', 'accomplishment', 'account', 'accurately', 'accused', 'act', 'acted', 'addressed', 'ado', 'advantages', 'adventure', 'adventures', 'advice', 'advise', 'advised', 'affair', 'affairs', 'afraid', 'agitation', 'ago', 'ah', 'aid', 'air', 'alarm', 'albert', 'allowed', 'amateur', 'america', 'american', 'americans', 'amid', 'analysis', 'analytical', 'anatomy', 'anderson', 'angry', 'animal', 'answer', 'answered', 'anxiety', 'anxiously', 'apology', 'appeal', 'appears', 'archive', 'argue', 'arm', 'armed', 'arms', 'army', 'arrived', 'art', 'ary', 'ascended', 'ashes', 'ask', 'asked', 'assert', 'assume', 'astronomy', 'atlantic', 'attain', 'attention', 'attic', 'attics', 'attracted', 'augustine', 'authorities', 'aversion', 'await', 'away', '